{
  network: 'sonic',
  exchanges: {
    EQUALIZER_ROUTER: '0xcC6169aA1E879d3a4227536671F85afdb2d23fAD',
    SHADOW_ROUTER: '0x5543c6176FEb9B4b179078205d7C29EEa2e2d695',
    BALANCER_VAULT: '0xBA12222222228d8Ba445958a75a0704d566BF2C8',
  },
  tokens: {
    USDC_e: '0x29219dd400f2Bf60E5a23d13Be72B486D4038894',
    WETH: '0x50c42dEAcD8Fc9773493ED674b675bE577f2634b',
    wS: '0x039e2fB66102314Ce7b64Ce5Ce3E5183bc94aD38',
    stS: '0xE5DA20F15420aD15DE0fa650600aFc998bbE3955',
    scUSD: '0xd3DCe716f3eF535C5Ff8d041c1A41C3bd89b97aE',
    bpt_rsb: '0xCd4D2b142235D5650fFA6A38787eD0b7d7A51c0C',
    bpt_sss: '0x374641076B68371e69D03C417DAc3E5F236c32FA',
    BPT_scUSD_stS: '0x25ca5451CD5a50AB1d324B5E64F32C0799661891',
    BPT_USDCe_stS: '0x713FB5036dC70012588d77a5B066f1Dd05c712d7',
    dUSDC_eV3: '0x6F6bda069FB05baB5E83B22FbDb54CBdF33f78ee',
    dwSV3: '0xCf4d737C38ef2ac9C7bdb4DbbC954b1932EA4a40',
    GEAR: '0x0fDbce271bea0d9819034cd09021e0bBE94be3Fd',
    S: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  },
  names: {
    USDC_e: 'USDC (Bridged)',
    WETH: 'WETH',
    wS: 'Wrapped Sonic',
    stS: 'Beets Staked Sonic',
    scUSD: 'Sonic USD',
    bpt_rsb: 'Ringing Stable Beets',
    bpt_sss: 'Staked Sonic Symphony',
    BPT_scUSD_stS: 'Put A Ring On It',
    BPT_USDCe_stS: 'Staked Sonic & Circle Concerto',
    dwSV3: 'dwSV3',
    dUSDC_eV3: 'dUSDC.eV3',
    GEAR: 'GEAR',
  },
  ids: {
    cvx3Crv: 9,
    cvxcrvFRAX: 100,
    cvxsteCRV: 25,
    cvxFRAX3CRV: 32,
    cvxLUSD3CRV: 33,
    cvxcrvPlain3andSUSD: 4,
    cvxgusd3CRV: 10,
    cvxcrvCRVETH: 61,
    cvxcrvCVXETH: 64,
    cvxcrvUSDTWBTCWETH: 188,
    cvxLDOETH: 149,
    cvxcrvUSDUSDC: 182,
    cvxcrvUSDUSDT: 179,
    cvxcrvUSDFRAX: 187,
    cvxcrvUSDETHCRV: 211,
    cvxGHOcrvUSD: 335,
    cvxllamathena: 401,
  },
  groups: {
    curvePools: {
      crvFRAX: 2,
      steCRV: 2,
      crvPlain3andSUSD: 4,
      crvCRVETH: 2,
      crvCVXETH: 2,
      crvUSDTWBTCWETH: 3,
      LDOETH: 2,
      crvUSDUSDC: 2,
      crvUSDUSDT: 2,
      crvUsUSDe: 2,
      llamathena: 2,
      crvUSDFRAX: 2,
      crvUSDETHCRV: 3,
      rETH_f: 2,
      DOLAFRAXBP3CRV_f: 2,
      crvUSDDOLA_f: 2,
      USDeUSDC: 2,
      FRAXUSDe: 2,
      USDecrvUSD: 2,
      FRAXsDAI: 2,
      DOLAsUSDe: 2,
      USDeDAI: 2,
      MtEthena: 2,
      GHOUSDe: 2,
      pufETHwstE: 2,
      GHOcrvUSD: 2,
      wstETHCRV: 2,
      '2CRV': 2,
      '3c-crvUSD': 3,
      crvUSDC: 2,
      crvUSDT: 2,
      crvUSDC_e: 2,
      USDEUSDC: 2,
      '3CRV': 3,
      ezETHWETH: 2,
      ezpzETH: 2,
      LBTCWBTC: 2,
      eBTCWBTC: 2,
      pumpBTCWBTC: 2,
      TriBTC: 3,
      '2BTC-f': 2,
      tETHwstETH: 2,
      tETHweETH: 2,
      pzETHstETH: 2,
      USDLUSDC: 2,
      FRAX3CRV: 2,
      LUSD3CRV: 2,
      GUSD3CRV: 2,
    },
    yearnCurveTokens: {
      yvCurve_stETH: 'steCRV',
      yvCURVE_FRAX: 'FRAX3CRV',
    },
    convexCurveTokens: {
      cvx3Crv: '3CRV',
      cvxcrvFRAX: 'crvFRAX',
      cvxsteCRV: 'steCRV',
      cvxFRAX3CRV: 'FRAX3CRV',
      cvxLUSD3CRV: 'LUSD3CRV',
      cvxcrvPlain3andSUSD: 'crvPlain3andSUSD',
      cvxgusd3CRV: 'GUSD3CRV',
      cvxcrvCRVETH: 'crvCRVETH',
      cvxcrvCVXETH: 'crvCVXETH',
      cvxcrvUSDTWBTCWETH: 'crvUSDTWBTCWETH',
      cvxLDOETH: 'LDOETH',
      cvxcrvUSDUSDC: 'crvUSDUSDC',
      cvxcrvUSDUSDT: 'crvUSDUSDT',
      cvxcrvUSDFRAX: 'crvUSDFRAX',
      cvxcrvUSDETHCRV: 'crvUSDETHCRV',
      cvxGHOcrvUSD: 'GHOcrvUSD',
      cvxllamathena: 'llamathena',
      stkcvx3Crv: '3CRV',
      stkcvxcrvFRAX: 'crvFRAX',
      stkcvxsteCRV: 'steCRV',
      stkcvxFRAX3CRV: 'FRAX3CRV',
      stkcvxLUSD3CRV: 'LUSD3CRV',
      stkcvxcrvPlain3andSUSD: 'crvPlain3andSUSD',
      stkcvxgusd3CRV: 'GUSD3CRV',
      stkcvxcrvCRVETH: 'crvCRVETH',
      stkcvxcrvCVXETH: 'crvCVXETH',
      stkcvxcrvUSDTWBTCWETH: 'crvUSDTWBTCWETH',
      stkcvxLDOETH: 'LDOETH',
      stkcvxcrvUSDUSDC: 'crvUSDUSDC',
      stkcvxcrvUSDUSDT: 'crvUSDUSDT',
      stkcvxcrvUSDFRAX: 'crvUSDFRAX',
      stkcvxcrvUSDETHCRV: 'crvUSDETHCRV',
      stkcvxGHOcrvUSD: 'GHOcrvUSD',
      stkcvxllamathena: 'llamathena',
      cvxcrvUSDT: 'crvUSDT',
    },
    balancerTokens: {
      '50WETH_50AURA': 2,
      B_80BAL_20WETH: 2,
      USDC_DAI_USDT: 3,
      B_rETH_STABLE: 2,
      weETH_rETH: 2,
      osETH_wETH_BPT: 2,
      ezETH_WETH_BPT: 2,
      sUSDe_USDC_BPT: 2,
      pumpBTC_WBTC_BPT: 2,
      eBTC_WBTC_BPT: 2,
      trenSTETH: 5,
      weETH_ezETH_rswETH: 3,
      GHO_USDT_USDC: 3,
      rsETH_WETH: 2,
      B_50WBTC_50WETH: 2,
      rsETH_wETH_Arb: 2,
      BPT_rETH_ETH: 2,
      BPT_WSTETH_ETH: 2,
      BPT_ROAD: 3,
      ECLP_wstETH_WETH: 2,
      wstETH_WETH_BPT: 2,
      wstETH_rETH_sfrxETH: 3,
      wstETH_rETH_cbETH: 3,
      cbETH_rETH_wstETH: 3,
      rETH_WETH_BPT_deprecated: 2,
      rETH_wETH_BPT: 2,
      '33AURA_33ARB_33BAL': 3,
      ezETH_wstETH: 2,
      bpt_ethtri: 3,
      bpt_rsb: 2,
      bpt_sss: 2,
      BPT_scUSD_stS: 2,
      BPT_USDCe_stS: 2,
      tETH_wstETH_BPT: 2,
    },
  },
  redstone: {
    USDC_e: {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: 'USDC',
      signersThreshold: 5,
    },
    WETH: {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: 'ETH',
      signersThreshold: 5,
    },
    wS: {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: 'S',
      signersThreshold: 5,
    },
    scUSD: {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: 'USDC',
      signersThreshold: 5,
    },
    crvFRAX: {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: 'crvFRAX',
      signersThreshold: 5,
    },
    sDAI: {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: 'sDAI',
      signersThreshold: 5,
    },
    steakLRT: {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: 'wstETH',
      signersThreshold: 5,
    },
    Re7LRT: {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: 'wstETH',
      signersThreshold: 5,
    },
    amphrETH: {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: 'wstETH',
      signersThreshold: 5,
    },
    rstETH: {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: 'wstETH',
      signersThreshold: 5,
    },
    pzETH: {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: 'wstETH',
      signersThreshold: 5,
    },
    '3CRV': {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: '3CRV',
      signersThreshold: 5,
    },
  },
  compositeRedstone: {
    stS: {
      type: 15,
      dataServiceId: 'redstone-primary-prod',
      dataId: 'stS_FUNDAMENTAL',
      signersThreshold: 5,
      token: '0x56a5b6267d6b8de8ade88455b9342787e49e2f1a',
    },
  },
}
